
BEGIN_KEY

KEY_DEF(PREVIOUS,   0,  VOL_ADVALUE_H,  RELEASE)
KEY_DEF(NEXT_PAGE,  0,  VOL_ADVALUE_M,  RELEASE)
KEY_DEF(REVERSE,    0,  VOL_ADVALUE_L,  RELEASE)


KEY_DEF(CANCEL,     1,  VOL_ADVALUE_L,  RELEASE)
KEY_DEF(UP,         1,  VOL_ADVALUE_M,  RELEASE)
KEY_DEF(DOWN,       1,  VOL_ADVALUE_H,  RELEASE)

KEY_DEF(CONFIRM,    2,  VOL_ADVALUE_L,  RELEASE)
KEY_DEF(LEFT,       2,  VOL_ADVALUE_M,  RELEASE)
KEY_DEF(RIGHT,      2,  VOL_ADVALUE_H,  RELEASE)

END_KEY
